version: '3'
services:
  web:
    image: weblogic10
    build: .
    restart: always
    volumes:
      - ./jdk7:/root/jdk/jdk7
      - ./jdk7/endorsed:/root/jdk/jdk1.6.0_45/jre/lib/endorsed
      - ./data/logs:/home/weblogic/idea/logs
      - ./config/config.xml:/root/Oracle/Middleware/user_projects/domains/base_domain/config/config.xml
      - ./config/setDomainEnv.sh:/root/Oracle/Middleware/user_projects/domains/base_domain/bin/setDomainEnv.sh
      - ./config/startWebLogic.sh:/root/Oracle/Middleware/user_projects/domains/base_domain/bin/startWebLogic.sh
      - ./autodeploy:/root/Oracle/Middleware/user_projects/domains/base_domain/autodeploy
      - ./webapps:/root/Oracle/Middleware/user_projects/domains/base_domain/servers/AdminServer/upload
    ports:
      - 7001:7001
      - 7002:7002
