version: '3'
services:
  web:
    image: weblogic10
    build: .
    restart: always
    volumes:
      - ./data/logs:/home/weblogic/idea/logs
#      - ./config/config.xml:/root/Oracle/Middleware/user_projects/domains/base_domain/config/config.xml
      - ./autodeploy:/root/Oracle/Middleware/user_projects/domains/base_domain/autodeploy
      - ./webapps:/root/Oracle/Middleware/user_projects/domains/base_domain/servers/AdminServer/upload
    ports:
      - 7001:7001
      - 7002:7002
