version: '3'
services:
    db:
        image: mysql:5
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

        restart: always
        volumes:
            - ./data:/var/lib/mysql:rw
            - ./conf:/etc/mysql/conf.d
            - ./initdb:/docker-entrypoint-initdb.d

        expose:
            - 3306
        environment:
            MYSQL_DATABASE: did
            MYSQL_ROOT_PASSWORD: root

    web:
        image: django_in_docker
        build: .
        command: ./launch.sh
        restart: always

        ports:
            - 8000:8000
        depends_on:
            - db
