version: '3'
services:
  web:
    image: weblogic12
    build: .
    restart: always
    volumes:
      - ./logs:/home/weblogic/idea/logs
      - ./config/domain.properties:/u01/oracle/properties
      - ./autodeploy:/u01/oracle/weblogic/user_projects/domains/base_domain/autodeploy
      - ./upload:/u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/upload
    ports:
      - 7001:7001
