version: '3'
services:
  web:
    image: weblogic12
    build: .
    restart: always
    volumes:
      - ./logs:/home/weblogic/idea/logs
      - ./config/domain.properties:/u01/oracle/properties
      - ./config/config.xml:/u01/oracle/weblogic/user_projects/domains/base_domain/config/config.xml
      - ./config/setDomainEnv.sh:/u01/oracle/weblogic/user_projects/domains/base_domain/bin/setDomainEnv.sh
      - ./autodeploy:/u01/oracle/weblogic/user_projects/domains/base_domain/autodeploy
      - ./webapps:/u01/oracle/weblogic/user_projects/domains/base_domain/servers/AdminServer/upload
    ports:
      - 7001:7001
