version: '3'
services:
    cache:
        image: "redis:4"
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - ./data:/data
        deploy:
            replicas: 1
        expose:
            - 6379

    viz:
        image: dockersamples/visualizer:stable
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
        ports:
            - "8080:8080"

    web:
        image: "hello_compose"
        build: .
        restart: always
        deploy:
            replicas: 1
        ports:
            - "5000:5000"
        depends_on:
            - cache
