version: '3'
services:
    cache:
        image: "redis:4"
        restart: always

        expose:
            - 6379

    web:
        image: "hello_compose"
        build: .
        restart: always

        ports:
            - "5000:5000"
        depends_on:
            - cache
