version: '3'
services:
    web:
        image: "hello_compose"
        build: .
        restart: always
        privileged: true

        ports:
            - "5000:5000"
        links:
            - redis

    redis:
        image: "redis:4"
