version: "3"
services:
    nginx:
        image: nginx_local:latest
        build: .
        restart: always
#        volumes:
#            - ./conf/nginx.conf:/etc/nginx/nginx.conf
#            - ./conf/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - nginx
#            - srv_srv
#            - client_client

networks:
    nginx:
        driver: bridge
#    srv_srv:
#        external: true
#    client_client:
#        external: true
