version: "3"
services:
  node:
    image: "node:8"
    build: .
    user: "node"
    working_dir: /home/node/app
    command: "npm start"

    environment:
      - NODE_ENV=production
    expose:
      - "8010"
