version: "3"
services:
    web:
        image: "node:8"
        build: .
        user: "node"
        command: "npm start"

        restart: always
        working_dir: /home/node/app

        volumes:
            - ./:/home/node/app

        ports:
            - "8010:8010"
        environment:
            - NODE_ENV=production
