version: '3'
services:
  jira:
    image: "jira:7.12.3"
    build: .
    hostname: jira
    ports:
      - "8080:8080"
      - "8081:8005"
    networks:
      - jira

networks:
  jira:
    driver: bridge
