version: '3'
services:
    db:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password

        restart: always
        volumes:
            - ./data:/var/lib/mysql
            - ./conf:/etc/mysql/conf.d
            - ./initdb:/docker-entrypoint-initdb.d

        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: did
            MYSQL_ROOT_PASSWORD: root

    dba:
        image: adminer
        restart: always
        
        ports:
            - 8080:8080
        depends_on:
            - db
