version: '3'
services:
    db:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password

        restart: always
        volumes:
            - ~/data:/var/lib/mysql:rw
            - ~/conf:/etc/mysql/conf.d
            - ./initdb:/docker-entrypoint-initdb.d

        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: django_in_docker
            MYSQL_ROOT_PASSWORD: root

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
