version: '3'
services:
    db:
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password

        restart: always
        # volumes:
        #     - ~/data:/var/lib/mysql:rw

        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=mysql_db
            - MYSQL_ROOT_PASSWORD=root

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
