version: "3"
services:
    nb:
        image: "jupyter/tensorflow-notebook"
        working_dir: /home/jovyan/work
        volumes:
            - ./code:/home/jovyan/work
        ports:
            - 8888:8888
